### ISSUE TITLE
how to get upland api key

### ISSUE THREAD

**Issue by wrramerson** [codekuu/upland-api#3]
I don't know where to get the upland api key

**Comment by codekuu** [comment]
You have to sign up and request a API key as a Upland Developer.

Here is a link to the developer portal:
https://developer.upland.me/

**Comment by wrramerson** [comment]
The site play.sandbox.upland.me is blocked.  I am not able to integrate could you help me

**Comment by codekuu** [comment]
@wrramerson I can not help you with that.
If you need any help to access the actual dev portal, contact upland via discord https://discord.gg/upland
